main_page: "https://www.otodom.pl/pl/wyniki"
offer_type: "sprzedaz"
apartament_type: "mieszkanie"
region: "podlaskie"
city: "bialystok"
distance_radius: 50
price_min:
price_max:
page_num: 1
limit: 72 
sys_sleep: 10


